'use strict';

/**
 * Scaffold generator: writes a generic poster project (index.html +
 * config.json) whose palette/typography come from the scanned tokens.
 * The poster follows the same adaptive pattern as the hand-made projects
 * (#canvas + shared/adaptive.js) so every format derives from the master.
 */

const fs = require('fs');
const path = require('path');
const config = require('../config');

function cap(text) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/**
 * Build the poster HTML injecting the tokens as CSS variables.
 * @param {{ name, title, tokens }} opts
 * @returns {string} html
 */
function buildHtml({ name, title, tokens }) {
  const c = tokens.colors;
  const f = tokens.fonts;

  const googleLink = f.googleImport
    ? `<link href="https://fonts.googleapis.com/css2?family=${f.googleImport}&display=swap" rel="stylesheet">`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
${googleLink}
<link rel="stylesheet" href="../../shared/styles/brand.css">
<link rel="stylesheet" href="../../shared/styles/adaptive.css">
<style>
    /* Generated by afiche scaffold — generic poster built from the app's
       global CSS (colors + fonts). Edit freely: it is just a base. */
    #canvas {
        --accent: ${c.accent};
        --accent2: ${c.accent2};
        --bg: ${c.background};
        --surface: ${c.surface};
        --text: ${c.text};
        --muted: ${c.muted};
        --line: ${c.border};
        container-type: size;
        display: grid;
        grid-template-rows: auto 1fr auto;
        padding: 8cqh 7cqw;
        gap: 3.6cqh;
        position: relative;
        overflow: hidden;
        background:
            radial-gradient(ellipse 70% 60% at 50% 0%, rgba(0,0,0,.25), transparent 58%),
            var(--bg);
        color: var(--text);
        font-family: '${f.body}', sans-serif;
    }
    .grid {
        position: absolute; inset: 0;
        background-image:
            linear-gradient(var(--line) 1px, transparent 1px),
            linear-gradient(90deg, var(--line) 1px, transparent 1px);
        background-size: 5.5cqw 5.5cqw;
        opacity: .25;
        mask-image: radial-gradient(ellipse 85% 70% at 50% 48%, #000 40%, transparent 100%);
        -webkit-mask-image: radial-gradient(ellipse 85% 70% at 50% 48%, #000 40%, transparent 100%);
    }
    .glow {
        position: absolute; width: 64cqw; height: 64cqw;
        left: 50%; top: 45%; transform: translate(-50%, -50%);
        background: radial-gradient(circle, var(--accent) 0%, transparent 62%);
        opacity: .16;
    }

    header { position: relative; z-index: 2; display: flex; align-items: center; justify-content: space-between; }
    .badge {
        display: inline-flex; align-items: center; gap: 1.4cqw;
        padding: 1.1cqh 2.2cqw; border: 1px solid var(--accent); border-radius: ${tokens.radius};
        font-family: '${f.mono}', monospace;
        font-size: clamp(12px, min(1.6cqw, 1.9cqh), 22px);
        font-weight: 600; letter-spacing: .16em; text-transform: uppercase;
        color: var(--accent); background: var(--surface);
    }
    .logo { font-size: clamp(18px, min(2.5cqw, 2.7cqh), 34px); font-weight: 800; letter-spacing: -.02em; color: var(--text); }
    .logo span { color: var(--accent); }

    main { position: relative; z-index: 2; display: flex; flex-direction: column; justify-content: center; gap: 2.4cqh; min-height: 0; text-align: center; }
    .kicker {
        font-family: '${f.mono}', monospace;
        font-size: clamp(11px, min(1.5cqw, 1.8cqh), 20px);
        letter-spacing: .34em; text-transform: uppercase; color: var(--accent);
    }
    h1 {
        margin: 0; font-weight: 800;
        font-size: clamp(46px, min(10.5cqw, 19cqh), 190px);
        line-height: .98; letter-spacing: -.045em; color: var(--text);
    }
    h1 em { font-style: normal; color: var(--accent); }
    .sub {
        margin: 0 auto;
        font-size: clamp(15px, min(2.6cqw, 3cqh), 36px);
        line-height: 1.45; color: var(--muted); max-width: 74cqw;
    }
    .sub b { color: var(--text); }

    ul.points {
        list-style: none; margin: .8cqh auto 0; padding: 0;
        display: flex; flex-wrap: wrap; justify-content: center; gap: 1.1cqh 1.8cqw;
    }
    ul.points li {
        display: flex; align-items: center; gap: .8em;
        font-family: '${f.mono}', monospace; font-weight: 600;
        font-size: clamp(12px, min(1.9cqw, 2.2cqh), 25px); color: var(--muted);
    }
    ul.points li::before {
        content: ''; flex: none; width: .85em; height: .85em; border-radius: ${tokens.radius};
        background: var(--accent); opacity: .8;
    }

    footer {
        position: relative; z-index: 2;
        display: flex; align-items: flex-end; justify-content: space-between; gap: 3cqw;
        padding-top: 2.4cqh; border-top: 1px solid var(--line);
    }
    .cta {
        display: inline-flex; align-items: center; gap: .8em;
        padding: clamp(12px, 1.6cqh, 28px) clamp(18px, 2.6cqw, 44px);
        border-radius: ${tokens.radius}; background: var(--accent);
        color: ${bgTextFor(c.accent)};
        font-size: clamp(14px, min(2cqw, 2.3cqh), 30px); font-weight: 800; letter-spacing: -.01em;
    }
    .meta {
        text-align: right; font-family: '${f.mono}', monospace;
        font-size: clamp(11px, min(1.9cqw, 2.1cqh), 23px); line-height: 1.6; color: var(--muted);
    }
    .meta strong { display: block; font-family: '${f.display}', sans-serif; font-size: 1.35em; font-weight: 800; color: var(--text); }

    #canvas[data-orient="square"] main { gap: 3.2cqh; }
    #canvas[data-orient="square"] h1 { font-size: clamp(52px, 12.5cqw, 150px); }
    #canvas[data-orient="square"] footer { flex-direction: column; align-items: stretch; }
    #canvas[data-orient="tall"] h1 { font-size: clamp(56px, 13.5cqw, 170px); }
    #canvas[data-orient="tall"] .sub { max-width: 92cqw; }
    #canvas[data-orient="tall"] footer { flex-direction: column; align-items: stretch; }
    #canvas[data-orient="tall"] .badge { font-size: clamp(10px, 2cqw, 20px); }
</style>
</head>
<body>
<div id="canvas" data-hf-id="hf-root">
    <div class="grid" data-hf-id="hf-grid"></div>
    <div class="glow" data-hf-id="hf-glow"></div>

    <header data-hf-id="hf-header">
        <div class="badge"><span id="kicker">scaffolded &#183; global css</span></div>
        <div class="logo" id="logo">${name}<span>&#183;</span></div>
    </header>

    <main data-hf-id="hf-main">
        <div class="kicker" id="kicker-title">design tokens from your code</div>
        <h1 id="title">${title.split(' ')[0]}<br><em>${title.split(' ').slice(1).join(' ') || 'app'}</em></h1>
        <p class="sub" id="subtitle">A generic poster generated from your app's <b>global styles</b> &#8212; colors, fonts and spacing detected automatically.</p>
        <ul class="points" id="points">
            <li>${c.accent}</li>
            <li>${f.display}</li>
            <li>${tokens.radius}</li>
        </ul>
    </main>

    <footer data-hf-id="hf-footer">
        <div class="meta" id="meta"><strong>${title}</strong>scaffolded from your css</div>
        <div class="cta" id="cta">See it live &#10148;</div>
    </footer>
</div>
<script src="../../shared/scripts/adaptive.js"></script>
</body>
</html>
`;
}

/** Contrasting ink for text sitting on the accent background. */
function bgTextFor(hex) {
  const { l } = require('./scan').hexToHsl(hex.replace('#', ''));
  return l < 0.55 ? '#ffffff' : '#111111';
}

/**
 * Write the project folder (config.json + index.html).
 * @param {{ name, title, tokens, dir }} opts
 */
function generate({ name, title, tokens, dir }) {
  const cfg = {
    name,
    title,
    description: 'Generic poster generated by `afiche --app` from the app global styles.',
    preset: 'wide',
    width: 1920,
    height: 1080,
    scale: 2,
    outputFormat: 'png',
    brand: {
      colors: {
        background: tokens.colors.background,
        surface: tokens.colors.surface,
        accent: tokens.colors.accent,
        accent2: tokens.colors.accent2,
        text: tokens.colors.text,
      },
      typography: {
        headlineFont: tokens.fonts.display,
        bodyFont: tokens.fonts.body,
        monoFont: tokens.fonts.mono,
      },
    },
  };

  fs.writeFileSync(path.join(dir, 'index.html'), buildHtml({ name, title, tokens }));
  fs.writeFileSync(path.join(dir, 'config.json'), JSON.stringify(cfg, null, 2));

  return { dir, config: cfg };
}

module.exports = { generate, buildHtml, bgTextFor };